### ISSUE TITLE
关于Docker安装

### ISSUE THREAD

**Issue by guadalikuan** [hlcfans/HLCTest#3]
希望第一步的docker安装能给出详细命令步骤，便于环境顺利搭建，谢谢！

**Comment by eric7733** [comment]
@guadalikuan 文档中已有docker安装步骤，在文档的最后。你可以看下。我们也会把docker安装步骤的内容调整下，放在文档前面，这样在阅读顺序上可能会比较好。
![image](https://user-images.githubusercontent.com/48508289/59481891-d4ed3780-8e98-11e9-8a1a-2731f6b54e5f.png)

**Comment by eric7733** [comment]
已经调整了docker安装步骤的位置 @guadalikuan

**Comment by guadalikuan** [comment]
谢谢！
